env:
  NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json
  NUGET_PROJECT_DIR: src
  NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs:
  deploy-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: |
          version=$(git tag -l --sort=-v:refname | head -n 1)
          version=${version/v/}
          dotnet build --configuration Release "${{env.NUGET_PROJECT_DIR}}" /p:Version="$version"
          dotnet pack --configuration Release "${{env.NUGET_PROJECT_DIR}}" --no-build --output . /p:Version="$version"
      - run: |
          dotnet nuget push *.nupkg --source "${{env.NUGET_SOURCE_URL}}" --api-key "${{env.NUGET_API_KEY}}" --skip-duplicate
